"""
Author: Ben Janis
Date: 2025

This source file is part of an example system for MITRE's 2025 Embedded System CTF
(eCTF). This code is being provided only for educational purposes for the 2025 MITRE
eCTF competition, and may not meet MITRE standards for quality. Use this code at your
own risk!

Copyright: Copyright (c) 2025 The MITRE Corporation
"""

import argparse
import json
from pathlib import Path
import struct
import hmac
import hashlib

from loguru import logger


def gen_subscription(
    secrets: bytes, device_id: int, start: int, end: int, channel: int
) -> bytes:
    """Generate the contents of a subscription, now with HMAC authentication.

    The output of this will be passed to the Decoder using ectf25.tv.subscribe

    :param secrets: Contents of the secrets file generated by ectf25_design.gen_secrets
    :param device_id: Device ID of the Decoder
    :param start: First timestamp the subscription is valid for
    :param end: Last timestamp the subscription is valid for
    :param channel: Channel to enable
    """
    # Load the json of the secrets file
    secrets = json.loads(secrets)

    # Ensure required secrets exist
    if "hmac_key" not in secrets:
        raise ValueError("Secrets file missing required 'hmac_key' entry.")

    # Convert HMAC key from hex
    hmac_key = bytes.fromhex(secrets["hmac_key"])

    # Ensure the channel is in the allowed list
    allowed_channels = secrets.get("channels", [])
    if channel not in allowed_channels:
        raise ValueError(f"Error: Channel {channel} is not in the allowed channel list.")

    # Pack the subscription data
    subscription_data = struct.pack("<IQQI", device_id, start, end, channel)

    # Generate HMAC signature to authenticate the subscription update
    hmac_signature = hmac.new(hmac_key, subscription_data, hashlib.sha256).digest()

    # Append HMAC to subscription data
    full_subscription = subscription_data + hmac_signature

    return full_subscription


def parse_args():  # DO NOT TOUCH!
    """Define and parse the command line arguments

    NOTE: Your design must not change this function
    """
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--force",
        "-f",
        action="store_true",
        help="Force creation of subscription file, overwriting existing file",
    )
    parser.add_argument(
        "secrets_file",
        type=argparse.FileType("rb"),
        help="Path to the secrets file created by ectf25_design.gen_secrets",
    )
    parser.add_argument("subscription_file", type=Path, help="Subscription output")
    parser.add_argument(
        "device_id", type=lambda x: int(x, 0), help="Device ID of the update recipient."
    )
    parser.add_argument(
        "start", type=lambda x: int(x, 0), help="Subscription start timestamp"
    )
    parser.add_argument("end", type=int, help="Subscription end timestamp")
    parser.add_argument("channel", type=int, help="Channel to subscribe to")
    return parser.parse_args()


def main():
    """Main function of gen_subscription

    You will likely not have to change this function
    """
    # Parse the command line arguments
    args = parse_args()

    try:
        subscription = gen_subscription(
            args.secrets_file.read(), args.device_id, args.start, args.end, args.channel
        )

        # Debugging info - Feel free to remove in production
        logger.debug(f"Generated subscription: {subscription.hex()}")

        # Open the file, erroring if the file exists unless the --force arg is provided
        with open(args.subscription_file, "wb" if args.force else "xb") as f:
            f.write(subscription)

        # Debugging output - Feel free to remove
        logger.success(f"Wrote subscription to {str(args.subscription_file.absolute())}")

    except Exception as e:
        logger.error(f"Error generating subscription: {str(e)}")


if __name__ == "__main__":
    main()
